# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DirectorPC.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DirectorWindow(object):
    def setupUi(self, DirectorWindow):
        DirectorWindow.setObjectName("DirectorWindow")
        DirectorWindow.resize(484, 600)
        DirectorWindow.setStyleSheet("background-color: rgb(62, 181, 236)")
        self.centralwidget = QtWidgets.QWidget(DirectorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 481, 541))
        self.tabWidget.setStyleSheet("font: 87 10pt \"Arial\";\n"
"color: black;\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.Department = QtWidgets.QWidget()
        self.Department.setObjectName("Department")
        self.textEditSection = QtWidgets.QTextEdit(self.Department)
        self.textEditSection.setGeometry(QtCore.QRect(20, 420, 341, 71))
        self.textEditSection.setStyleSheet("QTextEdit{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(150,150,150)\n"
"}\n"
"QTextEdit::hover{    \n"
"    border: 3px solid rgb(180, 180, 180);\n"
"}")
        self.textEditSection.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditSection.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditSection.setObjectName("textEditSection")
        self.listSection = QtWidgets.QListWidget(self.Department)
        self.listSection.setGeometry(QtCore.QRect(20, 20, 431, 381))
        self.listSection.setStyleSheet("background-color: white;")
        self.listSection.setObjectName("listSection")
        self.ButtonSection = QtWidgets.QPushButton(self.Department)
        self.ButtonSection.setGeometry(QtCore.QRect(380, 420, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(72)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ButtonSection.setFont(font)
        self.ButtonSection.setStyleSheet("QPushButton{    \n"
"    font: 87 72pt \"Arial\";\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    border: 3px solid rgb(180, 180, 180);\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"QPushButton::hover{\n"
"    color: black;\n"
"    background-color: white;\n"
"}")
        self.ButtonSection.setObjectName("ButtonSection")
        self.tabWidget.addTab(self.Department, "")
        self.SectionDirectors = QtWidgets.QWidget()
        self.SectionDirectors.setObjectName("SectionDirectors")
        self.listDirSec = QtWidgets.QListWidget(self.SectionDirectors)
        self.listDirSec.setGeometry(QtCore.QRect(20, 20, 431, 381))
        self.listDirSec.setStyleSheet("background-color: white;")
        self.listDirSec.setObjectName("listDirSec")
        self.textEditDirSec = QtWidgets.QTextEdit(self.SectionDirectors)
        self.textEditDirSec.setGeometry(QtCore.QRect(20, 420, 341, 71))
        self.textEditDirSec.setStyleSheet("QTextEdit{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(150,150,150)\n"
"}\n"
"QTextEdit::hover{    \n"
"    border: 3px solid rgb(180, 180, 180);\n"
"}")
        self.textEditDirSec.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditDirSec.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditDirSec.setObjectName("textEditDirSec")
        self.ButtonDirSec = QtWidgets.QPushButton(self.SectionDirectors)
        self.ButtonDirSec.setGeometry(QtCore.QRect(380, 420, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(72)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ButtonDirSec.setFont(font)
        self.ButtonDirSec.setStyleSheet("QPushButton{    \n"
"    font: 87 72pt \"Arial\";\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    border: 3px solid rgb(180, 180, 180);\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"QPushButton::hover{\n"
"    color: black;\n"
"    background-color: white;\n"
"}")
        self.ButtonDirSec.setObjectName("ButtonDirSec")
        self.tabWidget.addTab(self.SectionDirectors, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listDirSec_2 = QtWidgets.QListWidget(self.tab)
        self.listDirSec_2.setGeometry(QtCore.QRect(20, 20, 431, 381))
        self.listDirSec_2.setStyleSheet("background-color: white;")
        self.listDirSec_2.setObjectName("listDirSec_2")
        self.textEditDirSec_2 = QtWidgets.QTextEdit(self.tab)
        self.textEditDirSec_2.setGeometry(QtCore.QRect(20, 420, 341, 71))
        self.textEditDirSec_2.setStyleSheet("QTextEdit{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(150,150,150)\n"
"}\n"
"QTextEdit::hover{    \n"
"    border: 3px solid rgb(180, 180, 180);\n"
"}")
        self.textEditDirSec_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditDirSec_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditDirSec_2.setObjectName("textEditDirSec_2")
        self.ButtonDirSec_2 = QtWidgets.QPushButton(self.tab)
        self.ButtonDirSec_2.setGeometry(QtCore.QRect(380, 420, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(72)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ButtonDirSec_2.setFont(font)
        self.ButtonDirSec_2.setStyleSheet("QPushButton{    \n"
"    font: 87 72pt \"Arial\";\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    border: 3px solid rgb(180, 180, 180);\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"QPushButton::hover{\n"
"    color: black;\n"
"    background-color: white;\n"
"}")
        self.ButtonDirSec_2.setObjectName("ButtonDirSec_2")
        self.tabWidget.addTab(self.tab, "")
        self.labelNLPDir = QtWidgets.QLabel(self.centralwidget)
        self.labelNLPDir.setGeometry(QtCore.QRect(80, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelNLPDir.setFont(font)
        self.labelNLPDir.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: white")
        self.labelNLPDir.setTextFormat(QtCore.Qt.AutoText)
        self.labelNLPDir.setScaledContents(False)
        self.labelNLPDir.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNLPDir.setObjectName("labelNLPDir")
        DirectorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DirectorWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DirectorWindow)

    def retranslateUi(self, DirectorWindow):
        _translate = QtCore.QCoreApplication.translate
        DirectorWindow.setWindowTitle(_translate("DirectorWindow", "WCHAT"))
        self.textEditSection.setHtml(_translate("DirectorWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ButtonSection.setText(_translate("DirectorWindow", ">"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Department), _translate("DirectorWindow", "Відділ"))
        self.textEditDirSec.setHtml(_translate("DirectorWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ButtonDirSec.setText(_translate("DirectorWindow", ">"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SectionDirectors), _translate("DirectorWindow", "Директори секцій"))
        self.textEditDirSec_2.setHtml(_translate("DirectorWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ButtonDirSec_2.setText(_translate("DirectorWindow", ">"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DirectorWindow", "Склад"))
        self.labelNLPDir.setText(_translate("DirectorWindow", "Михайленко Дмитро (Директор)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DirectorWindow = QtWidgets.QMainWindow()
    ui = Ui_DirectorWindow()
    ui.setupUi(DirectorWindow)
    DirectorWindow.show()
    sys.exit(app.exec_())
