# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 400)
        LoginWindow.setStyleSheet("background-color: rgb(62, 181, 236)\n"
"")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainLabel = QtWidgets.QLabel(self.centralwidget)
        self.MainLabel.setGeometry(QtCore.QRect(135, 20, 130, 70))
        self.MainLabel.setStyleSheet("font: 75 48pt \"Arial\";\n"
"color: white")
        self.MainLabel.setObjectName("MainLabel")
        self.lineName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineName.setGeometry(QtCore.QRect(60, 120, 280, 40))
        self.lineName.setStyleSheet("QLineEdit{\n"
"    font: 12pt \"Arial\";\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(150,150,150)\n"
"}\n"
"QLineEdit::hover{    \n"
"    border: 3px solid rgb(180, 180, 180);\n"
"}\n"
"")
        self.lineName.setText("")
        self.lineName.setObjectName("lineName")
        self.linePassword = QtWidgets.QLineEdit(self.centralwidget)
        self.linePassword.setGeometry(QtCore.QRect(60, 180, 280, 40))
        self.linePassword.setStyleSheet("QLineEdit{\n"
"    font: 12pt \"Arial\";\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(150,150,150)\n"
"}\n"
"QLineEdit::hover{    \n"
"    border: 3px solid rgb(180, 180, 180);\n"
"}")
        self.linePassword.setText("")
        self.linePassword.setObjectName("linePassword")
        self.buttonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLogin.setGeometry(QtCore.QRect(130, 240, 140, 40))
        self.buttonLogin.setStyleSheet("QPushButton{\n"
"    font: 75 24pt \"Arial\";\n"
"    border-radius: 6px;\n"
"    border: 3px solid rgb(180, 180, 180);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(180, 180, 180);\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.buttonLogin.setObjectName("buttonLogin")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.MainLabel.setText(_translate("LoginWindow", "Вхід"))
        self.buttonLogin.setText(_translate("LoginWindow", "Увійти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
