# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SellerPC.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SellerWindow(object):
    def setupUi(self, SellerWindow):
        SellerWindow.setObjectName("SellerWindow")
        SellerWindow.resize(484, 600)
        SellerWindow.setStyleSheet("background-color: rgb(62, 181, 236)")
        self.centralwidget = QtWidgets.QWidget(SellerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 481, 541))
        self.tabWidget.setStyleSheet("font: 87 10pt \"Arial\";\n"
"color: black;\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.Department = QtWidgets.QWidget()
        self.Department.setObjectName("Department")
        self.textEditSellerSec = QtWidgets.QTextEdit(self.Department)
        self.textEditSellerSec.setGeometry(QtCore.QRect(20, 420, 341, 71))
        self.textEditSellerSec.setStyleSheet("QTextEdit{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(150,150,150)\n"
"}\n"
"QTextEdit::hover{    \n"
"    border: 3px solid rgb(180, 180, 180);\n"
"}")
        self.textEditSellerSec.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditSellerSec.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditSellerSec.setObjectName("textEditSellerSec")
        self.listSellerSec = QtWidgets.QListWidget(self.Department)
        self.listSellerSec.setGeometry(QtCore.QRect(20, 20, 431, 381))
        self.listSellerSec.setStyleSheet("background-color: white;")
        self.listSellerSec.setObjectName("listSellerSec")
        self.ButtonSellerSec = QtWidgets.QPushButton(self.Department)
        self.ButtonSellerSec.setGeometry(QtCore.QRect(380, 420, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(72)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ButtonSellerSec.setFont(font)
        self.ButtonSellerSec.setStyleSheet("QPushButton{    \n"
"    font: 87 72pt \"Arial\";\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    border: 3px solid rgb(180, 180, 180);\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"QPushButton::hover{\n"
"    color: black;\n"
"    background-color: white;\n"
"}")
        self.ButtonSellerSec.setObjectName("ButtonSellerSec")
        self.tabWidget.addTab(self.Department, "")
        self.Director = QtWidgets.QWidget()
        self.Director.setObjectName("Director")
        self.listSellerDir = QtWidgets.QListWidget(self.Director)
        self.listSellerDir.setGeometry(QtCore.QRect(20, 20, 431, 381))
        self.listSellerDir.setStyleSheet("background-color: white;")
        self.listSellerDir.setObjectName("listSellerDir")
        self.textEditSellerDir = QtWidgets.QTextEdit(self.Director)
        self.textEditSellerDir.setGeometry(QtCore.QRect(20, 420, 341, 71))
        self.textEditSellerDir.setStyleSheet("QTextEdit{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(150,150,150)\n"
"}\n"
"QTextEdit::hover{    \n"
"    border: 3px solid rgb(180, 180, 180);\n"
"}")
        self.textEditSellerDir.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditSellerDir.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditSellerDir.setObjectName("textEditSellerDir")
        self.ButtonSellerDir = QtWidgets.QPushButton(self.Director)
        self.ButtonSellerDir.setGeometry(QtCore.QRect(380, 420, 75, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(72)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ButtonSellerDir.setFont(font)
        self.ButtonSellerDir.setStyleSheet("QPushButton{    \n"
"    font: 87 72pt \"Arial\";\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    border: 3px solid rgb(180, 180, 180);\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"QPushButton::hover{\n"
"    color: black;\n"
"    background-color: white;\n"
"}")
        self.ButtonSellerDir.setObjectName("ButtonSellerDir")
        self.tabWidget.addTab(self.Director, "")
        self.labelNLPSeller = QtWidgets.QLabel(self.centralwidget)
        self.labelNLPSeller.setGeometry(QtCore.QRect(80, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.labelNLPSeller.setFont(font)
        self.labelNLPSeller.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: white")
        self.labelNLPSeller.setTextFormat(QtCore.Qt.AutoText)
        self.labelNLPSeller.setScaledContents(False)
        self.labelNLPSeller.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNLPSeller.setObjectName("labelNLPSeller")
        SellerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SellerWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SellerWindow)

    def retranslateUi(self, SellerWindow):
        _translate = QtCore.QCoreApplication.translate
        SellerWindow.setWindowTitle(_translate("SellerWindow", "WCHAT"))
        self.textEditSellerSec.setHtml(_translate("SellerWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ButtonSellerSec.setText(_translate("SellerWindow", ">"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Department), _translate("SellerWindow", "Відділ"))
        self.textEditSellerDir.setHtml(_translate("SellerWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ButtonSellerDir.setText(_translate("SellerWindow", ">"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Director), _translate("SellerWindow", "Склад"))
        self.labelNLPSeller.setText(_translate("SellerWindow", "Михайленко Дмитро (Продавець)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SellerWindow = QtWidgets.QMainWindow()
    ui = Ui_SellerWindow()
    ui.setupUi(SellerWindow)
    SellerWindow.show()
    sys.exit(app.exec_())
